# site settings
title: B.C.Kerswell
subtitle: PhD Candidate
email: buchanankerswell@u.boisestate.edu
description: Geoscientist with eclectic interests<br/> Amateur athlete & developer
baseurl: # the subpath of your site, e.g. /blog
url: http://buchanankerswell.github.io # the base hostname & protocol for your site
author:
street_address: 1916 S Grant Ave
city: Boise
state: ID
zip_code: 83706
country: United States of America
phone: +1 480 417 2797

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
github_url: https://github.com/buchanankerswell
researchgate_url: https://www.researchgate.net/profile/Buchanan_Kerswell
googlescholar_url: https://scholar.google.com/citations?hl=en&user=O7TM22kAAAAJ
orcid_url: https://orcid.org/0000-0003-0495-4162
osf_url: https://osf.io/sd5z3/

# build settings
markdown: kramdown
sass:
  style: compressed
